version: '2'
services:
    quakejs:
        container_name: quakejs
        environment:
            - SERVER=54.167.240.131
            - HTTP_PORT=80
        ports:
            - '80:80'
            - '27960:27960'
        image: 'treyyoder/quakejs:latest'
        volumes:
            - ./server.cfg:/quakejs/base/baseq3/server.cfg
